image:
  file: .gitpod.Dockerfile

tasks:
- command: pipenv install


ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
vscode:
  extensions:
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - torn4dom4n.latex-support@3.1.0:kOnkMkOz2UwnIF/pOupURw==
    - ms-python.python@2019.10.44104:fKYRb8X8FA37fMd+hgvv2A==